from util.from_type import *
class GeneralCommandType(CaseInsensitiveEnum):
    """This exists simply to identify a set of known commands."""
    BACK = "Back"
    CHANNEL_DOWN = "ChannelDown"
    CHANNEL_UP = "ChannelUp"
    DISPLAY_CONTENT = "DisplayContent"
    DISPLAY_MESSAGE = "DisplayMessage"
    GO_HOME = "GoHome"
    GO_TO_SEARCH = "GoToSearch"
    GO_TO_SETTINGS = "GoToSettings"
    GUIDE = "Guide"
    MOVE_DOWN = "MoveDown"
    MOVE_LEFT = "MoveLeft"
    MOVE_RIGHT = "MoveRight"
    MOVE_UP = "MoveUp"
    MUTE = "Mute"
    NEXT_LETTER = "NextLetter"
    PAGE_DOWN = "PageDown"
    PAGE_UP = "PageUp"
    PLAY = "Play"
    PLAY_MEDIA_SOURCE = "PlayMediaSource"
    PLAY_NEXT = "PlayNext"
    PLAY_STATE = "PlayState"
    PLAY_TRAILERS = "PlayTrailers"
    PREVIOUS_LETTER = "PreviousLetter"
    SELECT = "Select"
    SEND_KEY = "SendKey"
    SEND_STRING = "SendString"
    SET_AUDIO_STREAM_INDEX = "SetAudioStreamIndex"
    SET_REPEAT_MODE = "SetRepeatMode"
    SET_SHUFFLE_QUEUE = "SetShuffleQueue"
    SET_SUBTITLE_STREAM_INDEX = "SetSubtitleStreamIndex"
    SET_VOLUME = "SetVolume"
    TAKE_SCREENSHOT = "TakeScreenshot"
    TOGGLE_CONTEXT_MENU = "ToggleContextMenu"
    TOGGLE_FULLSCREEN = "ToggleFullscreen"
    TOGGLE_MUTE = "ToggleMute"
    TOGGLE_OSD = "ToggleOsd"
    TOGGLE_OSD_MENU = "ToggleOsdMenu"
    TOGGLE_STATS = "ToggleStats"
    UNMUTE = "Unmute"
    VOLUME_DOWN = "VolumeDown"
    VOLUME_UP = "VolumeUp"


