from util.from_type import *


class SessionMessageType(CaseInsensitiveEnum):
    """The different kinds of messages that are used in the WebSocket api."""
    ACTIVITY_LOG_ENTRY = "ActivityLogEntry"
    ACTIVITY_LOG_ENTRY_START = "ActivityLogEntryStart"
    ACTIVITY_LOG_ENTRY_STOP = "ActivityLogEntryStop"
    FORCE_KEEP_ALIVE = "ForceKeepAlive"
    GENERAL_COMMAND = "GeneralCommand"
    KEEP_ALIVE = "KeepAlive"
    LIBRARY_CHANGED = "LibraryChanged"
    PACKAGE_INSTALLATION_CANCELLED = "PackageInstallationCancelled"
    PACKAGE_INSTALLATION_COMPLETED = "PackageInstallationCompleted"
    PACKAGE_INSTALLATION_FAILED = "PackageInstallationFailed"
    PACKAGE_INSTALLING = "PackageInstalling"
    PACKAGE_UNINSTALLED = "PackageUninstalled"
    PLAY = "Play"
    PLAYSTATE = "Playstate"
    REFRESH_PROGRESS = "RefreshProgress"
    RESTART_REQUIRED = "RestartRequired"
    SCHEDULED_TASKS_INFO = "ScheduledTasksInfo"
    SCHEDULED_TASKS_INFO_START = "ScheduledTasksInfoStart"
    SCHEDULED_TASKS_INFO_STOP = "ScheduledTasksInfoStop"
    SCHEDULED_TASK_ENDED = "ScheduledTaskEnded"
    SERIES_TIMER_CANCELLED = "SeriesTimerCancelled"
    SERIES_TIMER_CREATED = "SeriesTimerCreated"
    SERVER_RESTARTING = "ServerRestarting"
    SERVER_SHUTTING_DOWN = "ServerShuttingDown"
    SESSIONS = "Sessions"
    SESSIONS_START = "SessionsStart"
    SESSIONS_STOP = "SessionsStop"
    SYNC_PLAY_COMMAND = "SyncPlayCommand"
    SYNC_PLAY_GROUP_UPDATE = "SyncPlayGroupUpdate"
    TIMER_CANCELLED = "TimerCancelled"
    TIMER_CREATED = "TimerCreated"
    USER_DATA_CHANGED = "UserDataChanged"
    USER_DELETED = "UserDeleted"
    USER_UPDATED = "UserUpdated"


